import type { Question, Section } from './types';

export const RATING_OPTIONS = [
  { value: 0, label: 'غير صحيح إطلاقًا' },
  { value: 1, label: 'صحيح إلى حد ما' },
  { value: 2, label: 'صحيح غالبًا' },
  { value: 3, label: 'صحيح جدًا' },
];

export const SECTIONS: Section[] = [
    { key: 'A', title: 'القسم أ: تشتت الانتباه ومشاكل التعلم', description: 'تركز هذه الأسئلة على الانتباه والتركيز والسلوكيات المتعلقة بالتحصيل الدراسي.' },
    { key: 'B', title: 'القسم ب: فرط الحركة والوظائف التنفيذية', description: 'يستفسر هذا القسم عن النشاط الحركي الزائد والمهارات مثل التخطيط والتنظيم.' },
    { key: 'C', title: 'القسم ج: السلوك العاطفي والسلوكي', description: 'يرجى تقييم السلوكيات المتعلقة بنوبات الغضب والتحدي والتعبير العاطفي.' },
    { key: 'D', title: 'القسم د: التفاعلات الاجتماعية والسلوك العام', description: 'تتعلق هذه الأسئلة بكيفية تفاعل طفلك مع أقرانه وأفراد أسرته.' },
];

export const QUESTIONS: Question[] = [
  // Section A: Inattention & Learning (20 questions)
  { id: 'q1', text: 'يفشل في الانتباه للتفاصيل الدقيقة أو يرتكب أخطاءً بسبب الإهمال في الواجبات المدرسية.', subscale: 'inattention', section: 'A' },
  { id: 'q2', text: 'يجد صعوبة في الحفاظ على انتباهه في المهام أو أثناء اللعب.', subscale: 'inattention', section: 'A' },
  { id: 'q3', text: 'يبدو كثير النسيان في الأنشطة اليومية (مثل الأعمال المنزلية، والمهمات).', subscale: 'inattention', section: 'A' },
  { id: 'q4', text: 'يجد صعوبة في تعلم وتذكر المعلومات الجديدة.', subscale: 'learning', section: 'A' },
  { id: 'q5', text: 'يتشتت انتباهه بسهولة بسبب المؤثرات الخارجية.', subscale: 'inattention', section: 'A' },
  { id: 'q6', text: 'يكافح من أجل متابعة التعليمات ويفشل في إكمال الواجبات المدرسية أو الأعمال المنزلية.', subscale: 'learning', section: 'A' },
  { id: 'q7', text: 'لا يبدو أنه يستمع عندما يتم التحدث إليه مباشرة.', subscale: 'inattention', section: 'A' },
  { id: 'q8', text: 'يتجنب أو يكره أو يتردد في المشاركة في المهام التي تتطلب مجهودًا عقليًا مستمرًا (مثل الواجبات المدرسية).', subscale: 'inattention', section: 'A' },
  { id: 'q9', text: 'غالبًا ما يفقد الأشياء الضرورية للمهام أو الأنشطة (مثل الألعاب، والواجبات المدرسية، والأقلام).', subscale: 'inattention', section: 'A' },
  { id: 'q10', text: 'يحتاج إلى تكرار التعليمات عدة مرات قبل أن يبدأ.', subscale: 'learning', section: 'A' },
  { id: 'q11', text: 'يظهر أداءً غير متسق في العمل المدرسي؛ جيد في يوم وسيء في اليوم التالي.', subscale: 'learning', section: 'A' },
  { id: 'q12', text: 'يستغرق وقتًا أطول من المعتاد لإكمال الواجبات المدرسية.', subscale: 'learning', section: 'A' },
  { id: 'q13', text: 'يجد صعوبة في فهم الأفكار المجردة.', subscale: 'learning', section: 'A' },
  { id: 'q14', text: 'ينتقل من نشاط غير مكتمل إلى آخر.', subscale: 'inattention', section: 'A' },
  { id: 'q15', text: 'يحلم في اليقظة أو يبدو ضائعًا في أفكاره.', subscale: 'inattention', section: 'A' },
  { id: 'q16', text: 'يجد صعوبة في القراءة أو فهم ما يقرأ.', subscale: 'learning', section: 'A' },
  { id: 'q17', text: 'لديه خط يد غير منظم أو فوضوي.', subscale: 'learning', section: 'A' },
  { id: 'q18', text: 'يبدو أنه لا يبذل جهدًا كافيًا في المهام الصعبة.', subscale: 'learning', section: 'A' },
  { id: 'q19', text: 'ينسى ما تعلمه بسرعة.', subscale: 'learning', section: 'A' },
  { id: 'q20', text: 'يفقد التركيز بسهولة أثناء أداء المهام.', subscale: 'inattention', section: 'A' },

  // Section B: Hyperactivity & Executive Function (20 questions)
  { id: 'q21', text: 'يتململ بيديه أو قدميه أو يتلوى في مقعده.', subscale: 'hyperactivity', section: 'B' },
  { id: 'q22', text: 'غالبًا ما يكون "في حركة مستمرة" أو يتصرف وكأنه "مدفوع بمحرك".', subscale: 'hyperactivity', section: 'B' },
  { id: 'q23', text: 'يجد صعوبة في تنظيم المهام والأنشطة.', subscale: 'executive', section: 'B' },
  { id: 'q24', text: 'يتحدث بشكل مفرط.', subscale: 'hyperactivity', section: 'B' },
  { id: 'q25', text: 'يجد صعوبة في انتظار دوره.', subscale: 'hyperactivity', section: 'B' },
  { id: 'q26', text: 'يتخذ قرارات متهورة دون التفكير في العواقب.', subscale: 'executive', section: 'B' },
  { id: 'q27', text: 'يترك مقعده في المواقف التي يتوقع منه البقاء جالسًا.', subscale: 'hyperactivity', section: 'B' },
  { id: 'q28', text: 'يجري أو يتسلق بشكل مفرط في مواقف غير مناسبة.', subscale: 'hyperactivity', section: 'B' },
  { id: 'q29', text: 'يجد صعوبة في اللعب أو المشاركة في الأنشطة الترفيهية بهدوء.', subscale: 'hyperactivity', section: 'B' },
  { id: 'q30', text: 'يطلق الإجابات قبل اكتمال الأسئلة.', subscale: 'hyperactivity', section: 'B' },
  { id: 'q31', text: 'يجد صعوبة في إدارة وقته.', subscale: 'executive', section: 'B' },
  { id: 'q32', text: 'غالبًا ما يماطل في بدء المهام.', subscale: 'executive', section: 'B' },
  { id: 'q33', text: 'غرفته أو مكتبه أو منطقة لعبه غير منظمة.', subscale: 'executive', section: 'B' },
  { id: 'q34', text: 'يجد صعوبة في التكيف مع التغييرات في الروتين.', subscale: 'executive', section: 'B' },
  { id: 'q35', text: 'يتصرف أولاً ثم يفكر لاحقًا.', subscale: 'executive', section: 'B' },
  { id: 'q36', text: 'يصر على أن تكون الأمور على طريقته.', subscale: 'executive', section: 'B' },
  { id: 'q37', text: 'يلمس أو يلعب بأي شيء في متناول يده.', subscale: 'hyperactivity', section: 'B' },
  { id: 'q38', text: 'لا يمكنه البقاء هادئًا؛ دائمًا ما يصدر ضوضاء أو يتحرك.', subscale: 'hyperactivity', section: 'B' },
  { id: 'q39', text: 'يبدأ مشاريع ولكنه نادرًا ما ينهيها.', subscale: 'executive', section: 'B' },
  { id: 'q40', text: 'لديه ذاكرة عاملة ضعيفة (على سبيل المثال، ينسى التعليمات متعددة الخطوات).', subscale: 'executive', section: 'B' },

  // Section C: Emotional & Behavioral Conduct (20 questions)
  { id: 'q41', text: 'يعاني من نوبات غضب أو يغضب بسهولة.', subscale: 'aggression', section: 'C' },
  { id: 'q42', text: 'يتحدى أو يرفض الامتثال لطلبات الكبار بشكل فعال.', subscale: 'aggression', section: 'C' },
  { id: 'q43', text: 'يلوم الآخرين على أخطائه أو سوء سلوكه.', subscale: 'aggression', section: 'C' },
  { id: 'q44', text: 'يبدو قلقًا أو مفرط النشاط.', subscale: 'hyperactivity', section: 'C' },
  { id: 'q45', text: 'يقاطع الآخرين أو يتدخل في شؤونهم (على سبيل المثال، يقتحم المحادثات).', subscale: 'peer', section: 'C' },
  { id: 'q46', text: 'سريع الانفعال أو يتضايق بسهولة من الآخرين.', subscale: 'aggression', section: 'C' },
  { id: 'q47', text: 'حاقد أو يسعى للانتقام.', subscale: 'aggression', section: 'C' },
  { id: 'q48', text: 'يستجيب بشكل مفرط للمواقف البسيطة.', subscale: 'executive', section: 'C' },
  { id: 'q49', text: 'مزاجي، مع تقلبات عاطفية سريعة.', subscale: 'executive', section: 'C' },
  { id: 'q50', text: 'يكذب لتجنب المتاعب أو للحصول على ما يريد.', subscale: 'aggression', section: 'C' },
  { id: 'q51', text: 'يدمر ممتلكاته أو ممتلكات الآخرين عمدًا.', subscale: 'aggression', section: 'C' },
  { id: 'q52', text: 'يجد صعوبة في قبول "لا" كإجابة.', subscale: 'aggression', section: 'C' },
  { id: 'q53', text: 'يظهر قليلًا من الشعور بالذنب أو الندم بعد سوء السلوك.', subscale: 'aggression', section: 'C' },
  { id: 'q54', text: 'يشعر بالإحباط بسهولة.', subscale: 'executive', section: 'C' },
  { id: 'q55', text: 'يتنمر على الآخرين أو يهددهم أو يخيفهم.', subscale: 'aggression', section: 'C' },
  { id: 'q56', text: 'يجد صعوبة في التحكم في انفعالاته.', subscale: 'executive', section: 'C' },
  { id: 'q57', text: 'يستخدم لغة بذيئة أو مسيئة.', subscale: 'aggression', section: 'C' },
  { id: 'q58', text: 'يبدو غير سعيد أو حزين أو مكتئب.', subscale: 'peer', section: 'C' },
  { id: 'q59', text: 'لديه عتبة منخفضة للإحباط.', subscale: 'executive', section: 'C' },
  { id: 'q60', text: 'يبدأ شجارات جسدية.', subscale: 'aggression', section: 'C' },

  // Section D: Social Interactions & General Conduct (20 questions)
  { id: 'q61', text: 'يجد صعوبة في تكوين صداقات أو الحفاظ عليها.', subscale: 'peer', section: 'D' },
  { id: 'q62', text: 'لا يراعي مشاعر الآخرين.', subscale: 'peer', section: 'D' },
  { id: 'q63', text: 'يتجادل مع الكبار.', subscale: 'aggression', section: 'D' },
  { id: 'q64', text: 'يبدو أنه يقع في مشاكل أكثر من الأطفال الآخرين في نفس عمره.', subscale: 'executive', section: 'D' },
  { id: 'q65', text: 'يفضل اللعب بمفرده.', subscale: 'peer', section: 'D' },
  { id: 'q66', text: 'يسيء فهم الإشارات الاجتماعية أو لغة الجسد.', subscale: 'peer', section: 'D' },
  { id: 'q67', text: 'يرفض مشاركة ألعابه أو ممتلكاته.', subscale: 'peer', section: 'D' },
  { id: 'q68', text: 'ينظر إليه أقرانه على أنه "متسلط" أو "مسيطر".', subscale: 'peer', section: 'D' },
  { id: 'q69', text: 'يقول أشياء غير لائقة أو مؤذية دون أن يدرك ذلك.', subscale: 'peer', section: 'D' },
  { id: 'q70', text: 'يعاني من الغش في الألعاب أو الأنشطة.', subscale: 'aggression', section: 'D' },
  { id: 'q71', text: 'يتجاهله أو يتجنبه الأطفال الآخرون.', subscale: 'peer', section: 'D' },
  { id: 'q72', text: 'يجد صعوبة في الانضمام إلى المجموعات أو المحادثات الجارية.', subscale: 'peer', section: 'D' },
  { id: 'q73', text: 'يتصرف بشكل أصغر من عمره.', subscale: 'executive', section: 'D' },
  { id: 'q74', text: 'يبحث عن الاهتمام المفرط من الكبار والأقران.', subscale: 'peer', section: 'D' },
  { id: 'q75', text: 'يخالف القواعد عمدًا.', subscale: 'aggression', section: 'D' },
  { id: 'q76', text: 'يخاطر جسديًا بشكل مفرط (على سبيل المثال، يتسلق عاليًا جدًا، يركب الدراجة بسرعة كبيرة).', subscale: 'executive', section: 'D' },
  { id: 'q77', text: 'يبدو غير مدرك للخطر.', subscale: 'executive', section: 'D' },
  { id: 'q78', text: 'غير قادر على رؤية وجهة نظر شخص آخر.', subscale: 'peer', section: 'D' },
  { id: 'q79', text: 'يواجه صعوبة في العمل كجزء من فريق.', subscale: 'peer', section: 'D' },
  { id: 'q80', text: 'يتهم الآخرين بالخيانة أو النية السيئة.', subscale: 'aggression', section: 'D' },
];
